const motds = [
    "#kb43ver",
    "You should donate to 43i.org",
    "Moco de Gorila",
    "A Who? A What? A LERODGE!",
    "You're telling me a SHRIMP fried this rice????",
    "BRING ME A SHRUBBERY!",
    "dems real apples",
    "What is the airspeed velocity of an unladen swallow?",
    "pizza my heart parking lot",
    "RIP JStark",
    "RIP Terry Davis",
    "RIP Ken Block",
    "os.remove('C://Windows/System32')",
    "sudo rm -rf",
    "waltuh...",
    "if you have a better fish pun, please let minnow",
    "chatgpt my beloved <3",
    "shadow wizard money gang",
    "Call me axparagus!",
    "'You'd better f*cking learn swedish' - Joakim Broden",
    "javascriptmaxxing",
    "TOMA TOMA TOMA TOMA",
    "it was hard to know who was more crazy, me or everyone else",
    "Life.... is Roblox",
    "hilarious entities",
    "*extremely loud incorrect buzzer*",
    "bomboclaat",
    "LGTM! :)",
    "sponsored by NordVPN",
    "sponsored by Gfuel",
    "sponsored by sponsors",
    "Torvalds is the goat",
    "i use arch btw",
    "send it"
  ];
  
export default motds;
  